blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/CyberShadow/aconfmgr/discussions/new?category=q-a
    about: Ask a question or request support for using aconfmgr.
  - name: Suggest an enhancement
    url: https://github.com/CyberShadow/aconfmgr/discussions/new?category=ideas
    about: Suggest an idea for a new feature or an enhancement.
  - name: Share a tip or configuration snippet
    url: https://github.com/CyberShadow/aconfmgr/wiki
    about: The project wiki hosts user-contributed add-ons.
